import uuid

from fastapi import APIRouter, Depends, Query, Request, Response, status

from app.core.exceptions import error_responses
from app.dependencies.auth import ManagerUser, StaffUser
from app.dependencies.database import DbSession
from app.models import BatchStatus
from app.schemas import Page
from app.schemas.batch import BatchCreate, BatchRead, BatchUpdate
from app.services import batch_service
from app.utils.helpers import client_ip
from app.utils.pagination import PageParams, page_meta, page_params

router = APIRouter(prefix="/batches", tags=["Batches"])


@router.get("", response_model=Page[BatchRead], summary="List batches",
            description="Ordered by expiry date. `days_remaining` is calculated live.",
            responses=error_responses(401, 422))
async def list_batches(
    user: StaffUser, db: DbSession, params: PageParams = Depends(page_params),
    product_id: uuid.UUID | None = None,
    status_filter: BatchStatus | None = Query(None, alias="status"),
    in_stock: bool | None = None,
) -> Page[BatchRead]:
    items, total = await batch_service.list_batches(
        db, user.company_id, params, product_id=product_id, status=status_filter, in_stock=in_stock
    )
    return Page(items=items, **page_meta(total, params))


@router.post("", response_model=BatchRead, status_code=status.HTTP_201_CREATED, summary="Create batch",
             description="Adds stock for a product with its own batch number and expiry date. Batch numbers are "
                         "unique per product; expiry cannot precede manufacturing. Records a PURCHASE movement. "
                         "Status is set immediately; alerts are generated by the expiry check. MANAGER or ADMIN.",
             responses=error_responses(401, 403, 404, 409, 422))
async def create_batch(data: BatchCreate, user: ManagerUser, request: Request, db: DbSession) -> BatchRead:
    return await batch_service.create_batch(db, user, data, client_ip(request))


@router.get("/{batch_id}", response_model=BatchRead, summary="Get batch",
            description="Single batch.", responses=error_responses(401, 404))
async def get_batch(batch_id: uuid.UUID, user: StaffUser, db: DbSession) -> BatchRead:
    return await batch_service.get_batch_read(db, user.company_id, batch_id)


@router.patch("/{batch_id}", response_model=BatchRead, summary="Update batch",
              description="Edit batch number or dates. Quantities change only via /sales and /inventory/adjust. "
                          "MANAGER or ADMIN.",
              responses=error_responses(400, 401, 403, 404, 409, 422))
async def update_batch(
    batch_id: uuid.UUID, data: BatchUpdate, user: ManagerUser, request: Request, db: DbSession
) -> BatchRead:
    return await batch_service.update_batch(db, user, batch_id, data, client_ip(request))


@router.delete("/{batch_id}", status_code=status.HTTP_204_NO_CONTENT, summary="Delete batch",
               description="Only batches without sales can be deleted (e.g. data-entry mistakes). MANAGER or ADMIN.",
               responses=error_responses(401, 403, 404, 409))
async def delete_batch(batch_id: uuid.UUID, user: ManagerUser, request: Request, db: DbSession) -> Response:
    await batch_service.delete_batch(db, user, batch_id, client_ip(request))
    return Response(status_code=status.HTTP_204_NO_CONTENT)
